### PR TITLE
Support Intel Mac

### LINKED ISSUE #22: Deno download fails on Intel Mac
Running `mix test` on Intel Mac results in:
```
[warning] Failed to download release from GitHub. Your platform is not supported for the provided version (os=darwin, architecture=amd64)
```

### PR DESCRIPTION
**Pull request by thomasif98**
Fixes #22 by adding support for Intel Mac.

After this fix, `mix test` on an Intel Mac succeeds:
```
08:24:23.540 [info] Downloading denoland/deno from https://github.com/denoland/deno/releases/download/v1.33.1/deno-x86_64-apple-darwin.zip
......................................................
Finished in 4.2 seconds (4.2s async, 0.00s sync)
9 doctests, 45 tests, 0 failures

Randomized with seed 814931
```

### CODE REVIEW

**Comment by adkron** [comment]
Thanks! 🤖 ❤️

**Comment by adkron** [comment]
#24 did the same thing but kept the original fall-through, so I pulled it in. Thank you for the work. 🤖 ❤️

**Comment by thomasif98** [comment]
Thanks @adkron. I thought of leaving in the original fall-through, but I couldn't see a situation that wasn't covered by the other two, based on the available downloads. Is there a case that I'm missing?

**Comment by adkron** [comment]
I was unsure if there was a reason to have it and didn't want to break anything by accident. I made an assumption that leaving it wouldn't break anything and I could update it later when I had time to dig into it.

You have a good point that there is probably nothing that would break.

**Comment by stentroad** [comment]
@thomasif98 FWIW: I also considered removing it, but then left it "just in case".  But yeah, think you're right that it's probably unnecessary.

**Review by adkron — APPROVED** [review]

**Comment by adkron** [comment]
You are correct. I went to double-check. 🤖 ❤️

**Comment by thomasif98** [comment]
Thank you. Next time, I will document my reasoning earlier.

**Pull request merged**
